### ISSUE TITLE
usb.core.USBError: [Errno 2] Entity not found

### ISSUE THREAD

**Issue by epcdiy** [xairy/lights-out#1]
I have use X230 with win10 x64
python version 3.13 x64
I use pip install libusb1
here is the error message:

write, request = 0x42, value = 0x00, index = 0x80
 => [Errno 2] Entity not found
Traceback (most recent call last):
  File "C:\Users\epc\Desktop\lightsoff\lights-out-main\led.py", line 74, in <module>
    arbitrary_write(0x80, 0x00)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\epc\Desktop\lightsoff\lights-out-main\led.py", line 67, in arbitrary_write
    request_write(0x42, value, addr, '')
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\epc\Desktop\lightsoff\lights-out-main\led.py", line 56, in request_write
    msg = dev.ctrl_transfer(bmRequestType=bmRequestType, bRequest=bRequest,
                        wValue=wValue, wIndex=wIndex,
                        data_or_wLength=data)
  File "C:\Users\epc\AppData\Local\Programs\Python\Python313\Lib\site-packages\usb\core.py", line 1071, in ctrl_transfer
    self._ctx.managed_open()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\epc\AppData\Local\Programs\Python\Python313\Lib\site-packages\usb\core.py", line 113, in wrapper
    return f(self, *args, **kwargs)
  File "C:\Users\epc\AppData\Local\Programs\Python\Python313\Lib\site-packages\usb\core.py", line 131, in managed_open
    self.handle = self.backend.open_device(self.dev)
                  ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\epc\AppData\Local\Programs\Python\Python313\Lib\site-packages\usb\backend\libusb1.py", line 804, in open_device
    return _DeviceHandle(dev)
  File "C:\Users\epc\AppData\Local\Programs\Python\Python313\Lib\site-packages\usb\backend\libusb1.py", line 652, in __init__
    _check(_lib.libusb_open(self.devid, byref(self.handle)))
    ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\epc\AppData\Local\Programs\Python\Python313\Lib\site-packages\usb\backend\libusb1.py", line 604, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 2] Entity not found

**Comment by xairy** [comment]
This error likely means that the USB device with the Vendor and Product IDs used in the script are not present on your system.

Note that you need to first use the `srom.py` and `patch_srom.py` scripts to upload the firmware with the universal implant to the webcam, and only then run the `led.py` script.

But also note that since you X230 appears to have different IDs for the webcam device, it's likely that you will need to rework the `patch_srom.py` script. Otherwise, uploading the modified firmware might brick the webcam.
