### ISSUE TITLE
USB device is present, id match your python code, but still Entity not found

### ISSUE THREAD

**Issue by epcdiy** [xairy/lights-out#2]
here is the id in your python code:
VENDOR_ID = 0x5986
PRODUCT_ID = 0x02d2

here is the picture of my win10 device manager:
![WX20241217-084516@2x](https://github.com/user-attachments/assets/3867947a-88c9-455e-90d6-8811ae5d0f56)

i think maybe os environment is difference between us?
could you tell me what about your environment info?
OS?
python version?
pyusb1 version?

C:\Users\epc\Desktop\lightsoff\lights-out-main>python srom.py read 1.bin
read, request = 0x07, value = 0x00, index = 0x00
 => [Errno 2] Entity not found
Traceback (most recent call last):
  File "C:\Users\epc\Desktop\lightsoff\lights-out-main\srom.py", line 106, in <module>
    read_srom(filename, 0x10000)
  File "C:\Users\epc\Desktop\lightsoff\lights-out-main\srom.py", line 90, in read_srom
    part = read_srom_once(i * 64, 64)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\epc\Desktop\lightsoff\lights-out-main\srom.py", line 85, in read_srom_once
    return request_read(0x07, 0, offset, length)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\epc\Desktop\lightsoff\lights-out-main\srom.py", line 43, in request_read
    msg = dev.ctrl_transfer(bmRequestType=bmRequestType, bRequest=bRequest,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\epc\Downloads\msys64\mingw64\lib\python3.12\site-packages\usb\core.py", line 1071, in ctrl_transfer
    self._ctx.managed_open()
  File "C:\Users\epc\Downloads\msys64\mingw64\lib\python3.12\site-packages\usb\core.py", line 113, in wrapper
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\epc\Downloads\msys64\mingw64\lib\python3.12\site-packages\usb\core.py", line 131, in managed_open
    self.handle = self.backend.open_device(self.dev)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\epc\Downloads\msys64\mingw64\lib\python3.12\site-packages\usb\backend\libusb1.py", line 804, in open_device
    return _DeviceHandle(dev)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\epc\Downloads\msys64\mingw64\lib\python3.12\site-packages\usb\backend\libusb1.py", line 652, in __init__
    _check(_lib.libusb_open(self.devid, byref(self.handle)))
  File "C:\Users\epc\Downloads\msys64\mingw64\lib\python3.12\site-packages\usb\backend\libusb1.py", line 604, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 2] Entity not found

**Comment by xairy** [comment]
I use Linux, so probably other info won't be applicable to your case.

Do you run the script as the Administrator (or whatever root user is called on Windows)?

This is most likely a Windows-specific issue, so otherwise I don't have any tips to resolve it.

**Comment by epcdiy** [comment]
could you tell me which Linux distribution do you use?
I just want to replicate it again.

btw，I have use Administrator, but result is the same

**Comment by epcdiy** [comment]
ok I got it! windows should install a driver for pyusb first 
you can close this issue now!

**Comment by xairy** [comment]
Perfect!
